-- Active: 1702171397384@@localhost@3306@TP_BD_3GI
USE TP_BD_3GI;

-- III-1/ Création des tables EMP et DEPT
CREATE TABLE IF NOT EXISTS EMP (
    EMPNO NUMERIC(7),
    ENAME VARCHAR(25),
    JOB VARCHAR(25),
    MGR NUMERIC(7),
    HIREDATE DATE,
    SAL NUMERIC(9, 2),
    COMM NUMERIC(9, 2),
    DEPTNO NUMERIC(7)
);

CREATE TABLE IF NOT EXISTS DEPT (
    DEPTNO NUMERIC(7),
    DNAME VARCHAR(25),
    LOC VARCHAR(25)
);

-- III-36/ (Suite)
-- Création de la table SALGRADE
CREATE TABLE IF NOT EXISTS SALGRADE (
  GRADE INT,
  LOSAL NUMERIC(9, 2),
  HISAL NUMERIC(9, 2)
);