USE TP_BD_3GI;

-- II-1/ Création de la table MY_EMPLOYEE
CREATE TABLE IF NOT EXISTS MY_EMPLOYEE (
    ID NUMERIC(4) NOT NULL,
    LAST_NAME VARCHAR(25),
    FIRST_NAME VARCHAR(25),
    USERID VARCHAR(8),
    SALARY NUMERIC(9, 2)
);