-- I-0/ Création de la BD TP_BD_3GI 
CREATE DATABASE IF NOT EXISTS TP_BD_3GI;
USE TP_BD_3GI;

-- I-1/ Création de la table DEPARTEMENT
CREATE TABLE IF NOT EXISTS DEPARTEMENT (
    ID NUMERIC(7),
    NAME VARCHAR(25)
);

-- I-3/ Création de la table EMPLOYEE 
CREATE TABLE IF NOT EXISTS EMPLOYEE (
    ID NUMERIC(7),
    LAST_NAME VARCHAR(25),
    FIRST_NAME VARCHAR(25),
    DEPT_ID NUMERIC(7)
);

-- I-5/ Création de la table EMPLOYEE2 
CREATE TABLE IF NOT EXISTS EMPLOYEE2 (
    EMPNO NUMERIC(7), --*
    ENAME VARCHAR(25), --*
    DEPTNO NUMERIC(7)
);